# Use root/example as user/password credentials
version: '3.7'
services:
  db:
    container_name: "miadok_db"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "miadok"
      MYSQL_USER: "command_user"
      MYSQL_PASSWORD: "keycode23"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name: "miadok_web_app"
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app/
networks:
  default:
volumes:
  mysql_data: