version: '3.9'
services:
  db:
    container_name: "miadok_db"
    # platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
  # redis:
  #   image: "redis:7-alpine"
  #   container_name: redis-server
  api:
    container_name: "miadok_api"
    build:
      context: .
      dockerfile: app.Dockerfile
    networks:
      - default
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:5432
      # STORAGE_HOST: redis
    volumes:
      - .:/app/
  web:
    container_name: "miadok_web"
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      WAIT_HOSTS: api:8080
    volumes:
      - .:/app/
networks:
  default: