version: '3.9'
services:
  db:
    container_name: "miadok_db"
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
  redis:
    container_name: "miadok_redis"
    image: "redis:7-alpine"
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - "6379"
    environment:
      REDIS_PASSWORD: 54321
  api:
    container_name: "miadok_api"
    build:
      context: .
      dockerfile: api.Dockerfile
    networks:
      - default
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      WAIT_HOSTS: db:5432, redis:6379
      # STORAGE_HOST: redis:6379
    volumes:
      - .:/app/
  web:
    container_name: "miadok_web"
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
    environment:
      WAIT_HOSTS: api:8080
    volumes:
      - .:/app/
networks:
  default: