// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "miadok-chaladok/internal/model"
)

// IListsUseCase is an autogenerated mock type for the IListsUseCase type
type IListsUseCase struct {
	mock.Mock
}

// GetFilterLists provides a mock function with given fields: ctx
func (_m *IListsUseCase) GetFilterLists(ctx context.Context) (*model.FilterListsResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFilterLists")
	}

	var r0 *model.FilterListsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.FilterListsResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.FilterListsResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.FilterListsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIListsUseCase creates a new instance of IListsUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIListsUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IListsUseCase {
	mock := &IListsUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
