// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "miadok-chaladok/internal/model"
)

// IOptionUseCase is an autogenerated mock type for the IOptionUseCase type
type IOptionUseCase struct {
	mock.Mock
}

// GetCartItems provides a mock function with given fields: ctx, request
func (_m *IOptionUseCase) GetCartItems(ctx context.Context, request *model.GetCartItemsRequest) ([]model.OptionItemResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetCartItems")
	}

	var r0 []model.OptionItemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetCartItemsRequest) ([]model.OptionItemResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetCartItemsRequest) []model.OptionItemResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OptionItemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.GetCartItemsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIOptionUseCase creates a new instance of IOptionUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOptionUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOptionUseCase {
	mock := &IOptionUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
