// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "miadok-chaladok/internal/model"
)

// IProductUseCase is an autogenerated mock type for the IProductUseCase type
type IProductUseCase struct {
	mock.Mock
}

// GetProductDescription provides a mock function with given fields: ctx, request
func (_m *IProductUseCase) GetProductDescription(ctx context.Context, request *model.GetProductDescriptionRequest) (*model.ProductDescriptionResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetProductDescription")
	}

	var r0 *model.ProductDescriptionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetProductDescriptionRequest) (*model.ProductDescriptionResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetProductDescriptionRequest) *model.ProductDescriptionResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ProductDescriptionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.GetProductDescriptionRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductsByFilterPaginated provides a mock function with given fields: ctx, request
func (_m *IProductUseCase) GetProductsByFilterPaginated(ctx context.Context, request *model.GetProductsByFilterPaginatedRequest) ([]model.ProductPreviewResponse, int64, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetProductsByFilterPaginated")
	}

	var r0 []model.ProductPreviewResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetProductsByFilterPaginatedRequest) ([]model.ProductPreviewResponse, int64, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetProductsByFilterPaginatedRequest) []model.ProductPreviewResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ProductPreviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.GetProductsByFilterPaginatedRequest) int64); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *model.GetProductsByFilterPaginatedRequest) error); ok {
		r2 = rf(ctx, request)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetSuggestions provides a mock function with given fields: ctx, request
func (_m *IProductUseCase) GetSuggestions(ctx context.Context, request *model.GetSuggestionsRequest) ([]model.ProductPreviewResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetSuggestions")
	}

	var r0 []model.ProductPreviewResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetSuggestionsRequest) ([]model.ProductPreviewResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetSuggestionsRequest) []model.ProductPreviewResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ProductPreviewResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.GetSuggestionsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIProductUseCase creates a new instance of IProductUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProductUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProductUseCase {
	mock := &IProductUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
