// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "miadok-chaladok/internal/model"
)

// IReviewUseCase is an autogenerated mock type for the IReviewUseCase type
type IReviewUseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *IReviewUseCase) Create(ctx context.Context, request *model.CreateReviewRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateReviewRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByProductIDPaginated provides a mock function with given fields: ctx, request
func (_m *IReviewUseCase) GetByProductIDPaginated(ctx context.Context, request *model.GetReviewsByProductIDRequest) ([]model.ReviewDescriptionResponse, int64, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetByProductIDPaginated")
	}

	var r0 []model.ReviewDescriptionResponse
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetReviewsByProductIDRequest) ([]model.ReviewDescriptionResponse, int64, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetReviewsByProductIDRequest) []model.ReviewDescriptionResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ReviewDescriptionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.GetReviewsByProductIDRequest) int64); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *model.GetReviewsByProductIDRequest) error); ok {
		r2 = rf(ctx, request)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewIReviewUseCase creates a new instance of IReviewUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIReviewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IReviewUseCase {
	mock := &IReviewUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
