---

debug: false
log:
  level: 6
cors:
  allow-origins:
    - "http://localhost"
    - "https://localhost"
app:
  port: 8080
store-secret: "6731a2da-6481-40bd-865b-7762158de022"
storage:
  host: "storage"
  port: 6379
  password: 54321
  db: 0
database:
  driver: "postgres"
  host: "db"
  port: 5432
  user: "miadok_manager"
  password: "54321"
  dbname: "miadok_db"
  pool:
    idle: 10
    max: 100
    lifetime: 300