---

debug: true
log:
  level: 6
app:
  port: 8080
web:
  host: "localhost"
  port: 3000
store-secret: "6731a2da-6481-40bd-865b-7762158de022"
storage:
  host: "localhost"
  port: 6379
  password: 54321
  db: 0
database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "miadok_manager"
  password: "54321"
  dbname: "miadok_db"
  pool:
    idle: 10
    max: 100
    lifetime: 300