---

debug: false
store-secret: "6731a2da-6481-40bd-865b-7762158de022"
redis:
  host: "redis"
  port: 6379
  password: 54321
  db: 0
database:
  driver: "postgres"
  host: "db"
  port: 5432
  user: "miadok_manager"
  password: "54321"
  dbname: "miadok_db"