name: Backend test
on:
  push:
    branches:
      - main
      - feature/**
      - ci/**
      - bug/**
      - test/**
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      # Check-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      # Set up go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      # Run go vet
      - name: Run go vet
        run: go vet ./...
      # Run staticcheck (bug & performance & style rules check)
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
      # Run tests
      - name: Run tests
        run: go test -race -vet=off ./...
  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      # Check-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      # Verify dependencies
      - name: Verify dependencies
        run: go mod verify
      # Build project
      - name: Build
        run: go build -v ./...