name: Backend test
on:
  push:
    branches:
      - main
      - feature/**
      - ci/**
      - bug/**
      - test/**
  pull_request:
    branches:
      - main
jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      # Check-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: false
      # Run golangci-lint
      - name: Run linters
          uses: golangci/golangci-lint-action@v3
          with:
            version: v1.56
      # Get dependencies
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      # Build project
      - name: Build
        run: go build ./...
      # Run tests
      - name: Run tests
        run: go test -v -vet=off ./...